syntax on
set nu
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4

nmap <C-n> : NERDTreeToggle<CR>

" -- Pluggins --

set laststatus=2

call plug#begin()

Plug 'https://github.com/itchyny/lightline.vim.git'

Plug 'preservim/nerdtree'

call plug#end()

