syntax on
set nu
set relativenumber
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set mouse=a
set modeline

autocmd FileType haskell setlocal shiftwidth=2 softtabstop=2 expandtab " for Haskell Files

let g:loaded_matchparen = 1

" -- Pluggins --


set laststatus=2 " - nerdtree

nmap <C-n> : NERDTreeToggle<CR>

call plug#begin()

Plug 'itchyny/lightline.vim'

Plug 'preservim/nerdtree'

Plug 'jiangmiao/auto-pairs'

Plug 'dense-analysis/ale'

call plug#end()

source ~/.vim/plugins-config/ale/ale.vim
