syntax on
set nu
set relativenumber
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set mouse=a
set modeline

let g:loaded_matchparen = 1

" -- Pluggins --

let g:ale_sign_highlight_linenrs = 0
set laststatus=2 " - nerdtree

nmap <C-n> : NERDTreeToggle<CR>

call plug#begin()

Plug 'itchyny/lightline.vim'

Plug 'preservim/nerdtree'

Plug 'jiangmiao/auto-pairs'

Plug 'dense-analysis/ale'

call plug#end()

source ~/.vim/plugins-config/ale/ale.vim
